postgresql: &postgresql
  adapter: postgresql
  encoding: utf8
  min_messages: warning
  pool: 5
  username: postgres
  host: localhost

development:
  <<: *postgresql
  database: production_tbr

production:
  <<: *postgresql
  database: production_tbr

test: &TEST
  <<: *postgresql
  database: test_tbr
